name: Generate videos

on:
  pull_request:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install system dependencies
      run: |
        sudo apt-get update
        bash setup.sh
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Run
      run: |
        python3 a_sorted_affair.py -s 100 all
