name: Generate and publish videos

on:
  release:
    types: [created]

jobs:
  generate_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install system dependencies
      run: |
        bash setup.sh
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Run
      run: |
        bash generate_all.sh 10000
