name: Tag

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install git -y
    - name: Tag commit with version
      run: |
        bash scripts/tag.sh
