name: Tag

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Tag commit with version
      run: |
        LAST=$(git describe --abbrev=0)
        NEXT=$((LAST+1))

        echo "Previous version: ${LAST}"
        echo "New version:      ${NEXT}"
        
        bash scripts/tag.sh
