name: Tag

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: jconstam/a_sorted_affair
          releases-only: false
        id: octokit
      - name: Get New Tag
        run: |
          CURR_TAG=${{ steps.octokit.outputs.tag }}
          echo ::set-output name=NEW_TAG::$((CURR_TAG+1))
        id: gen_tag
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.gen_tag.outputs.NEW_TAG }}
          release_name: Release ${{ steps.gen_tag.outputs.NEW_TAG }}
          body: |
            Release version ${{ steps.gen_tag.outputs.NEW_TAG }}
          draft: false
          prerelease: false
